### ISSUE TITLE
Error for Fossil Machine.

### ISSUE THREAD

**Issue by manyogurt** [Arcaryx/Cobblemon-Integrations#8] opened 2024-06-05 23:10 UTC
![2024-06-06_01 06 58](https://github.com/Arcaryx/Cobblemon-Integrations/assets/44836817/c1fb9f1f-a57b-458b-ae4a-982ee031dc95)
![2024-06-06_01 07 09](https://github.com/Arcaryx/Cobblemon-Integrations/assets/44836817/50774a4a-49f3-4e1c-b2da-ff79e660c6c7)
![2024-06-06_01 07 19](https://github.com/Arcaryx/Cobblemon-Integrations/assets/44836817/5296b36f-12b2-4d47-9190-893cf04bfd61)

![image](https://github.com/Arcaryx/Cobblemon-Integrations/assets/44836817/5a422261-cc90-4925-ba1f-e4ce483cb762)

It said to report it, so I am! :)
It's a problem with Jade Integration through your mod. The screenshots from on a clean client with only Cobblemon, Cobblemon Integrations, Jade, and Fabric API on it.

**Comment by Arcaryx** [comment] 2024-06-27 22:53
This should be fixed with https://github.com/Arcaryx/Cobblemon-Integrations/commit/0b511dac0545d479ceb644d09fbae33522d56522. This was caused by Cobblemon 1.5.0 -> 1.5.2. This will be resolved in the next version (should be 1.0.6).

**Comment by Baboobraz** [comment] 2024-07-02 11:52
I'm having this issue as well and I would like to add that sometimes it causes the chunk that the fossil setup is in plus a few surrounding chunks facing east to not load blocks at all and only load entities. Below is a screenshot of my modded world where this is happening. I do have a lot of other mods installed, although I am certain its the fossil setup because I had this problem in a different part of my world and removing the setup fixed it. Now that its in my warehouse, the issue is back in that area of my world. 
![2024-07-02_04 51 04](https://github.com/Arcaryx/Cobblemon-Integrations/assets/85592003/c5567e84-2a08-4b52-9170-3508d2ce9f34)

**Comment by Arcaryx** [comment] 2024-07-27 14:19
@Baboobraz Please let me know if this still occurs in version 1.0.6 (and isolate to confirm my mod is responsible).

**Closed** 2024-10-02 09:35 UTC
